Claims page was broken, discovered the bug is in the ODBC Adapter.
springbuk/odbc_adapter pull request #10
Opened 2022-03-17 20:04 UTC by ACerka-Springbuk

## Source

https://springbuk-glass.atlassian.net/browse/MOJ-121

## Problem

Claims page was broken upon using the new odbc adapter in master

## Solution

dbms_type_cast needs to return rows at the end. Also added code to raise exceptions, since currently these circumstances shouldn't be encountered and if that changes spontaneously (such as through an snowflake odbc driver update) we want to know rather than silently have nil values.

## Testing/QA Notes

As there are no tests currently for `snowflake`, the best thing to test this is to load it up locally, run some queries, and check the `ruby` types of the returned results.

##  Post Merge Notes

This PR will require additional PRs be merged into springbuk, edison, and data management

2022-03-17 21:16 UTC, JaredAlford approved these changes

2022-03-18 00:50 UTC, bfredenburg requested changes

2022-03-18 00:50 UTC, bfredenburg commented on lib/odbc_adapter/database_statements.rb
> +                        raise "Unhandled column type: #{column_type}"
Exceptions should not be raised here. the data should be returned as-is (a string) and let the application code deal with the values.

2022-03-18 00:52 UTC, bfredenburg commented on lib/odbc_adapter/database_statements.rb
> +                        raise "Unhandled column type: #{column_type}"
Also, the first loop should not be a map. Replace
columns.map.with_index do |column, col_index|
with 
columns.each_with_index do |column, col_index|

2022-03-18 02:39 UTC, bfredenburg commented on lib/odbc_adapter/database_statements.rb
> +                        raise "Unhandled column type: #{column_type}"
I am working on corrections to avoid the garbage collection error.

2022-03-18 03:18 UTC, bfredenburg approved these changes

2022-03-18 04:13 UTC, Darinth commented on lib/odbc_adapter/database_statements.rb
> +                        raise "Unhandled column type: #{column_type}"
Big fan of the changes I see. Particularly handling the scale of numerics. What was the cause of the garbage collection error? I was only noticing it when I was writing to the console and assumed it was something related to that.

2022-03-18 10:49 UTC, bfredenburg commented on lib/odbc_adapter/database_statements.rb
> +                        raise "Unhandled column type: #{column_type}"
The garbage collection warning appears to be triggered by `@connection.types()`.

2022-03-18 10:57 UTC, bfredenburg commented on lib/odbc_adapter/database_statements.rb
> +                        raise "Unhandled column type: #{column_type}"
During previous work on odbc_adapter I created a table (sandbox3.bob_test.datatypes) with a column for each data type Snowflake appears to support. When selecting from this table the ODBC driver does not actually return the integer types for the columns created as integer types (i1 - i6). Even Snowflake's UI shows columns created as integer and bigint as number(38,0).

2022-03-18 13:34 UTC, Xenox473 approved these changes

2022-03-18 14:05 UTC, merged